USE master;
ALTER DATABASE [foy1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

RESTORE DATABASE [foy1]
FROM DISK = 'D:\SQLVeriTabani\foy1_backup.bak'
WITH REPLACE;
GO

ALTER DATABASE [foy1] SET MULTI_USER;
